### PR TITLE
Fix SVG files not having a thumbnail

### LINKED ISSUE #703: No Thumbnail with SVG image
I am trying to add an SVG image to a jgiven report as an attachment: 

```
 public Attachment generateUml() {
        final String interactions = testInteractions.stream().map(it ->
                it.getFrom() + " -> " + it.getTo() + " [[" + linkToAttachment(it) + "]] : " + it.getType().name().toLowerCase()
        ).collect(Collectors.joining("\n", "@startuml\n", "\n@enduml\n"));
        final SourceStringReader reader = new SourceStringReader(interactions);

        try (final ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            if(reader.outputImage(outputStream, new FileFormatOption(FileFormat.SVG)) == null){
                throw new RuntimeException("unable to generate image:" + outputStream);
            };
            return Attachment.fromText(outputStream.toString(), MediaType.imageUtf8("svg+xml; charset=utf-8"))
                    .withTitle("System Interactions")
                    .withFileName("interactions-" + UUID.randomUUID().toString().substring(0, 10));
        } catch (IOException e) {
            throw new RuntimeException("could not generate sequence diagram", e);
        }
    }
```
However, there are a number of problems:

1. The image has no thumbnail version (and so looks strange in the report). Clicking the link renders the image correctly in the browser.

2. inlining it does so correctly but renders it unable to function correctly (the image has hover overs and links in it). You cannot click the image to open it in the browser, however.

Screenshot 2021-08-04 at 11 53 20

3. I cannot just use the SVG MediaType enum  provided as this cannot be rendered correctly by the report. I need to do the `MediaType.imageUtf8("svg+xml; charset=utf-8")` dance for jgiven to render it at all.. it gets the incorrect file extension when it's mediatype is assessed by the report generation step.

What is the correct way to do this? Please help.

### PR DESCRIPTION
**Pull request by andru47**
Fixes #703

### CODE REVIEW

File: jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java [hunk 1]
```diff
@@ -195,4 +201,78 @@ static BufferedImage scaleDown( BufferedImage before ) {
...
+        try {
+            transcoder.transcode(transcoderInput, transcoderOutput);
+        } catch (TranscoderException e) {
+            e.printStackTrace();
+            log.error("Error while transcoding the svg file to png. Is the svg formatted correctly?");
+            return null;
+        }
+
+        try {
+            fis.close();
```
Comment (corbym) [inline jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java:268]: Could you use a try-with-resources here? You could catch separate exceptions if you are concerned about logging the right exception and messages.

File: jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java [hunk 2]
```diff
@@ -195,4 +201,78 @@ static BufferedImage scaleDown( BufferedImage before ) {
...
+
+        return dimension;
+    }
+
+    void createSVGThumbFile(File targetFile, String base64Image, Dimension dimension) {
+        String xmlFormat = getXMLFormat(base64Image, dimension);
+        try {
+            FileWriter fileWriter = new FileWriter(targetFile);
+            fileWriter.write(xmlFormat);
+            fileWriter.close();
```
Comment (corbym) [inline jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java:229]: This will hold the file open if an exception is thrown.

Try-with-resources might be better, or failing this try-catch-finally will do

File: jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java [hunk 3]
```diff
@@ -195,4 +201,78 @@ static BufferedImage scaleDown( BufferedImage before ) {
...
+        ByteArrayOutputStream baos = new ByteArrayOutputStream();
+
+        transcoderInput.setInputStream(fis);
+        transcoderOutput.setOutputStream(baos);
+
+        try {
+            transcoder.transcode(transcoderInput, transcoderOutput);
+        } catch (TranscoderException e) {
+            e.printStackTrace();
+            log.error("Error while transcoding the svg file to png. Is the svg formatted correctly?");
```
Comment (corbym) [inline jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java:263]: Has this been left in by mistake?

File: jgiven-html5-report/src/test/java/com/tngtech/jgiven/report/html5/Html5AttachmentGeneratorTest.java [hunk 4]
```diff
@@ -87,6 +87,42 @@ public void testFindingAndGeneratingAttachmentsInAllSteps() throws IOException {
...
 
+    @Test
+    public void testGetImageDimensions() {
+        Html5AttachmentGenerator generator = new Html5AttachmentGenerator(temporaryFolderRule.getRoot());
+        assertThat(generator.getImageDimension(BINARY_SAMPLE)).isEqualTo(new Dimension(22, 22));
+    }
+
+    @Test
+    public void testPNGConvertor() {
+        Html5AttachmentGenerator generator = new Html5AttachmentGenerator(temporaryFolderRule.getRoot());
```
Comment (corbym) [inline jgiven-html5-report/src/test/java/com/tngtech/jgiven/report/html5/Html5AttachmentGeneratorTest.java:97]: This could be a bit more DRY, it's repeated below.

**Review by l-1squared — DISMISSED** [review]

File: jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java [hunk 5]
```diff
@@ -28,171 +13,263 @@
...
+                    File thumbFile = getThumbnailFileFor(targetFile);
+                    byte[] thumbnail = compressToThumbnail(attachment.getValue(), extension);
+                    Files.write(thumbnail, thumbFile);
                 }
-                Files.write( BaseEncoding.base64().decode( attachment.getValue() ), targetFile );
+                Files.write(BaseEncoding.base64().decode(attachment.getValue()), targetFile);
             } else {
-                Files.write( attachment.getValue(), targetFile, Charsets.UTF_8 );
+                Files.write(attachment.getValue().getBytes(Charsets.UTF_8), targetFile);
+                if (attachment.getMediaType().equals(com.tngtech.jgiven.attachment.MediaType.SVG_UTF_8.toString())) {
```
[the remark this answers is not in the document]
Comment (l-1squared) [reply jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java:148]: ah understood it

File: jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java [hunk 6]
```diff
@@ -28,171 +13,263 @@
...
+import org.apache.batik.transcoder.TranscoderException;
+import org.apache.batik.transcoder.TranscoderInput;
+import org.apache.batik.transcoder.TranscoderOutput;
+import org.apache.batik.transcoder.image.PNGTranscoder;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 
 class Html5AttachmentGenerator extends ReportModelVisitor {
-    private static final Logger log = LoggerFactory.getLogger( Html5AttachmentGenerator.class );
+    private static final Logger log = LoggerFactory.getLogger(Html5AttachmentGenerator.class);
```
[the remark this answers is not in the document]
Comment (andru47) [reply jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java:32]: Yeah, I think it would be good to have a Util class for xml.

**Review by corbym — APPROVED** [review]

**Comment by corbym** [comment]
Not that I count 😂

File: jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java [hunk 7]
```diff
@@ -28,171 +13,249 @@
...
+        String base64PNGImage = getPNGFromSVG(initialSVG);
+        byte[] scaledDownInBytes = compressToThumbnail(base64PNGImage, "png");
+        Dimension imageDimension = getImageDimension(scaledDownInBytes);
+        String base64ScaledDownContent = BaseEncoding.base64().encode(scaledDownInBytes);
+        createSVGThumbFile(thumbnailSVG, base64ScaledDownContent, imageDimension);
+    }
+
+    Dimension getImageDimension(byte[] givenImage) {
+        Dimension dimension = new Dimension();
+        try (ByteArrayInputStream bais = new ByteArrayInputStream(givenImage)) {
```
Comment (fudler) [inline jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java:212]: It's just a minor thing, but could we maybe come up with a better naming here? Maybe just something like "inputstream" instead of "bias".

File: jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java [hunk 8]
```diff
@@ -28,171 +13,249 @@
...
+    String getPNGFromSVG(File givenSVG) {
+        PNGTranscoder transcoder = new PNGTranscoder();
+        TranscoderInput transcoderInput = new TranscoderInput();
+        TranscoderOutput transcoderOutput = new TranscoderOutput();
+
+        try (FileInputStream fis = new FileInputStream(givenSVG);
+             ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
+            transcoderInput.setInputStream(fis);
+            transcoderOutput.setOutputStream(baos);
+
```
Comment (fudler) [inline jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java:248]: Same as above.

**Review by fudler — COMMENTED** [review]
Technically it looks fine, just a bit nitpicking ;)

**Review by fudler — APPROVED** [review]

**Comment by corbym** [comment]
Just a follow up question: when will this be released?

Thanks

M

**Comment by andru47** [comment]
Hi @corbym,
We are planning to do a release tomorrow.
